# Generated by Django 6.0.5 on 2026-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="content",
            field=models.TextField(default="test1"),
            preserve_default=False,
        ),
    ]
